# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stock_categories.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StockCategoriesDialog(object):
    def setupUi(self, StockCategoriesDialog):
        StockCategoriesDialog.setObjectName("StockCategoriesDialog")
        StockCategoriesDialog.setWindowModality(QtCore.Qt.WindowModal)
        StockCategoriesDialog.resize(498, 349)
        StockCategoriesDialog.setModal(True)
        self.stockCatsLabel = QtWidgets.QLabel(StockCategoriesDialog)
        self.stockCatsLabel.setGeometry(QtCore.QRect(180, 10, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.stockCatsLabel.setFont(font)
        self.stockCatsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.stockCatsLabel.setObjectName("stockCatsLabel")
        self.idDisplay = QtWidgets.QTextEdit(StockCategoriesDialog)
        self.idDisplay.setEnabled(False)
        self.idDisplay.setGeometry(QtCore.QRect(30, 280, 31, 21))
        self.idDisplay.setObjectName("idDisplay")
        self.stockCategoryDisplay = QtWidgets.QTextEdit(StockCategoriesDialog)
        self.stockCategoryDisplay.setGeometry(QtCore.QRect(80, 280, 261, 21))
        self.stockCategoryDisplay.setObjectName("stockCategoryDisplay")
        self.addStockCatsButton = QtWidgets.QPushButton(StockCategoriesDialog)
        self.addStockCatsButton.setGeometry(QtCore.QRect(30, 320, 62, 19))
        self.addStockCatsButton.setObjectName("addStockCatsButton")
        self.updateStockCatsButton = QtWidgets.QPushButton(StockCategoriesDialog)
        self.updateStockCatsButton.setGeometry(QtCore.QRect(180, 320, 62, 19))
        self.updateStockCatsButton.setObjectName("updateStockCatsButton")
        self.deleteStockCatsButton = QtWidgets.QPushButton(StockCategoriesDialog)
        self.deleteStockCatsButton.setGeometry(QtCore.QRect(260, 320, 62, 19))
        self.deleteStockCatsButton.setObjectName("deleteStockCatsButton")
        self.cancelStockCatsButton = QtWidgets.QPushButton(StockCategoriesDialog)
        self.cancelStockCatsButton.setGeometry(QtCore.QRect(370, 320, 62, 19))
        self.cancelStockCatsButton.setObjectName("cancelStockCatsButton")
        self.stockCatsTableView = QtWidgets.QTableView(StockCategoriesDialog)
        self.stockCatsTableView.setGeometry(QtCore.QRect(30, 40, 431, 231))
        self.stockCatsTableView.setObjectName("stockCatsTableView")
        self.stockCatsPlusButton = QtWidgets.QPushButton(StockCategoriesDialog)
        self.stockCatsPlusButton.setGeometry(QtCore.QRect(460, 220, 31, 51))
        self.stockCatsPlusButton.setObjectName("stockCatsPlusButton")
        self.displayOrderCombo = QtWidgets.QComboBox(StockCategoriesDialog)
        self.displayOrderCombo.setGeometry(QtCore.QRect(361, 280, 101, 22))
        self.displayOrderCombo.setObjectName("displayOrderCombo")

        self.retranslateUi(StockCategoriesDialog)
        self.cancelStockCatsButton.clicked.connect(StockCategoriesDialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(StockCategoriesDialog)

    def retranslateUi(self, StockCategoriesDialog):
        _translate = QtCore.QCoreApplication.translate
        StockCategoriesDialog.setWindowTitle(_translate("StockCategoriesDialog", "Stock Categories"))
        self.stockCatsLabel.setText(_translate("StockCategoriesDialog", "Stock Categories"))
        self.addStockCatsButton.setText(_translate("StockCategoriesDialog", "Add"))
        self.updateStockCatsButton.setText(_translate("StockCategoriesDialog", "Update"))
        self.deleteStockCatsButton.setText(_translate("StockCategoriesDialog", "Delete"))
        self.cancelStockCatsButton.setText(_translate("StockCategoriesDialog", "Cancel"))
        self.stockCatsPlusButton.setText(_translate("StockCategoriesDialog", "+"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StockCategoriesDialog = QtWidgets.QDialog()
    ui = Ui_StockCategoriesDialog()
    ui.setupUi(StockCategoriesDialog)
    StockCategoriesDialog.show()
    sys.exit(app.exec_())
